apiVersion: v1
kind: Secret
metadata:
  name: github-runner-secrets
type: Opaque
data:
  RUNNER_NAME: Z2hhLXJ1bm5lcg==
  GITHUB_REPO: Si1ILVRyYW4vZ2hhLXJ1bm5lcg==
  GITHUB_RUNNER_TOKEN: QUlSUVI2N1EzVzRMUU5TNzJTQ01DUkRIUzRTMjY=