apiVersion: v1
kind: Secret
metadata:
  name: github-runner-secrets
type: Opaque
data:
  RUNNER_NAME: <base64-encoded-runner-name>
  GITHUB_REPO: <base64-encoded-github-repo>
  GITHUB_RUNNER_TOKEN: <base64-encoded-github-runner-token>